### PR TITLE
Add task directly from terminal

### PR DESCRIPTION
**Pull request by codeaholicguy**
Implement adding task directly from terminal.

Example:

`worque todo --task "Make pull request"`

Task `"Make pull request"` will be append to the end of current notes file.

### CODE REVIEW

**Comment by qcam** [comment]
@codeaholicguy thanks for the PR, doesn't `echo "some new tasks" >> worque todo` do the same thing?

Other than that I think --append is more self-explanatory than --task.

**Comment by codeaholicguy** [comment]
@huynhquancam in context `todo` I think `--task` is reasonable, `--append` is ok for this case but it is a verb, like an action than param name, thoughts?

**Comment by qcam** [comment]
`worque todo` is actually designed to work like `touch` in UNIX.

How about a brand-new subcommand like `worque append` or `worque add-task`?

**Comment by codeaholicguy** [comment]
we still need specific notes file, so I think `worque todo --append-task` is suitable, how do you think?

**Comment by qcam** [comment]
Awesome! :+1:

**Comment by qcam** [comment]
Great could you help to document it in the readme before I can merge?

**Comment by codeaholicguy** [comment]
Of course, I will do that.

**Comment by qcam** [comment]
Perfect thank you!

**Pull request merged**
